Added support for paste.
alefragnani/vscode-copy-word pull request #41
Opened 2022-03-05 21:22 UTC by dudeNumber4

I just can't figure out how to debug my command.  I don't know how/where `registerCommands` is supposed to get called.  Reference [feature request](https://github.com/alefragnani/vscode-copy-word/issues/40).

2022-03-16 23:36 UTC, alefragnani requested changes
Please, update the PR with the provided review. 

Once updated, I'll try out.

Thank you

2022-03-16 23:36 UTC, alefragnani commented on package.json
> +  "version": "3.7.0",
Undo these changes. I'm not sure the new `Paste` command needs to update the extension's name/description

2022-03-16 23:36 UTC, alefragnani commented on package.json
> +    "typescript": "^4.6.2"
Undo this change. There is no need to update TS.

2022-03-16 23:36 UTC, alefragnani commented on package.json
> +    "typescript": "^4.6.2"
Undo this change. There is no need to update TS.

2022-03-16 23:36 UTC, alefragnani commented on README.md
> +# What's new in Copy Word in Cursor 3.7
Thanks, but undo file changes. Whenever I update the extension, I like to review its content.

2022-03-16 23:36 UTC, alefragnani commented on README.md
> +# What's new in Copy Word in Cursor 3.7
Thanks, but undo file changes. Whenever I update the extension, I like to review its content.

2022-03-16 23:36 UTC, alefragnani commented on CHANGELOG.md
> +
Thanks, but undo file changes. Whenever I update the extension, I like to review its content.

2022-03-16 23:36 UTC, alefragnani commented on CHANGELOG.md
> +
Thanks, but undo file changes. Whenever I update the extension, I like to review its content.

2022-03-16 23:46 UTC, alefragnani commented
Hi @dudeNumber4 ,

First of all, thank you for your PR. I made a few comments, and would like you to take a look. Those 3 files `README.md`, `CHANGELOG.md` and `package-lock.json` could be reverted (removed from PR) and only package.json needs update. The extension's code itself, seems to be ok.

About debugging, I've noticed this issue after updating the extension to use **esbulid**. It requires you to be _built_ (`npm run build`) every time you update the code, because there it has no `watch` feature. I'm reverting this change in #43 , because web extension samples uses **WebPack** for easier packaging. With **WebPack**, which scripts supports watch, whenever you change the code, the debug works as expected.

I can merge #43 into main, so you could update your branch and retry with WebPack. Otherwise, simply follow these esbuild instructions to properly debug the extension. What do you prefer?

Thank you

2022-03-19 22:23 UTC, dudeNumber4 commented
I was able to debug; it should be good to merge.

2022-03-26 14:53 UTC, dudeNumber4 commented
Is there anything else blocking this from being merged?

2022-03-26 15:31 UTC, alefragnani commented
Not at all. 

Just my free time to test/merge 😉

2022-03-26 15:31 UTC, alefragnani commented
My plans are for this weekend

2022-03-29 23:39 UTC, merged

2022-03-30 00:00 UTC, alefragnani commented
Just published v3.7.0 with your PR.

This new release also works on the **web** (github.dev and vscode.dev)

Thank you