Cut/Copy line if at left margin.
alefragnani/vscode-copy-word pull request #45
Opened 2022-04-03 22:46 UTC by dudeNumber4

2022-04-13 01:18 UTC, alefragnani commented
Hi @dudeNumber4 ,

First of all, thanks for your PR. Please, open an issue about the feature you are proposing, so we can gather feedback from other users.

About this specific feature, it should need at least an _opt-in_ setting. Simply because I created the extension exactly to avoid copying the entire line when nothing is selected 😆 .

Thank you

2022-04-13 01:42 UTC, alefragnani requested changes

2022-04-17 22:48 UTC, dudeNumber4 commented on src/commands.ts
> +            if (isAtStartOfLine(editor)) {
The refactor doesn't work.  If start of line and configured, we finish the entire command, not just select.  So you'd have to check conditions yet again after calling the new func.

2022-04-17 23:08 UTC, dudeNumber4 commented on src/commands.ts
> +                await env.clipboard.writeText(getCurrentLine(editor));
Amazing that I read right over `editor.action.clipboardPasteAction`.  I was just thinking, "why doesn't VS Code work as expected?

2022-06-09 20:29 UTC, dudeNumber4 commented
@alefragnani , can this be merged?  Issues have been addressed.

2022-07-22 00:45 UTC, alefragnani commented
Sorry for the late reply. Had some other priorities to deal with.
I'm planning to look the PR this weekend.

Thank you

2022-08-05 01:45 UTC, merged